spring.application.name=cacaormpresa
spring.datasource.drive-class-name=
spring.datasource.url=
sprint.datasource.username=
spring.datasource.pasword=

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
